# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDECanarias
                                 A QGIS plugin
 Este complemento permite realizar búsquedas en la toponimia de Canarias.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-03-06
        copyright            : (C) 2018 by Félix José Hernández
        email                : fhernandeze@grafcan.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IDECanarias class from file IDECanarias.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .idecanarias import IDECanarias
    return IDECanarias(iface)
